name: mars
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.13+17

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

  firebase_core: ^2.4.0 
  cloud_firestore: ^4.2.0 
  firebase_auth: 
  firebase_analytics:  
  firebase_storage:
  firebase_dynamic_links: 
  firebase_messaging: 
  firebase_core_platform_interface: 
  firebase_ui_firestore:

  flutter_local_notifications: ^9.5.3+1
  cloud_functions:
  google_sign_in:
  google_maps_flutter: ^2.4.0
  sign_in_with_apple: ^3.0.0
  flutter_riverpod:

  path_provider:
  flutter_native_timezone:
  font_awesome_flutter: ^10.1.0
  cached_network_image:
  flare_flutter:
  share_plus: 6.3.2
  package_info:
  image_picker:
  carousel_slider:
  intl:
  google_fonts:
  badges: ^2.0.1
  path: ^1.8.0
  get_it: ^7.2.0
  hive: ^2.2.3 
  hive_flutter:
  dots_indicator:
  crypto:
  drift:
  sqlite3_flutter_libs:
  sliding_up_panel:
  geolocator:
  url_launcher:
  percent_indicator: ^4.2.2
  qr_flutter:
  flutter_barcode_scanner:
  ticket_widget:
  syncfusion_flutter_calendar:
  flutter_colorpicker:
  flutter_native_splash:
  intl_phone_number_input:
  pin_code_fields:
  dotted_line:
  scroll_date_picker:
  permission_handler:
  notification_permissions:
  firebase_app_check: ^0.1.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons:
  drift_dev: ^2.3.2
  build_runner: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo_trans_croped.png"
  image_path_ios: "assets/imgs/logo_dark.png"
  adaptive_icon_background: "#1F3469"
  adaptive_icon_foreground: "assets/imgs/logo_trans_croped.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#1F3469"
  image: assets/imgs/logo_trans.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/google_fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
